spring.application.name=financialtracker

spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://localhost:5432/financial_tracker
spring.datasource.username=postgres
spring.datasource.password=LLLLLLLLLLL
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.mail.host=smtp.someserver.dom
spring.mail.port=465
spring.mail.username=username
spring.mail.password=password
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable = true